# Generated by Django 5.2.3 on 2025-06-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='unumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='upassword',
        ),
    ]
